esphome:
  name: "mq135-air-quality"
 
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

wifi:
  min_auth_mode: WPA2
  power_save_mode: NONE
  fast_connect: True
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password    
  ap:
 
      
logger:
 
web_server:
  log: True
  local: True
  port: 80
  include_internal: False
  version: 3
  id: webserver_sort
  sorting_groups:
    - id: info_group
      name: "Environmental Life Data"
      sorting_weight: 10
    - id: critic_group
      name: "Critical works"
      sorting_weight: 60    
  
api:

ota:
  - platform: esphome
    password: "xxxXXXxxx"

captive_portal:

globals:

#The load resistance on the board. Value in KiloOhms
  - id: RLOAD
    type: float
    restore_value: no
    initial_value: '1.025'

#Calibration resistance at atmospheric CO2 level. Outdoor calibration data
  - id: RZERO
    type: float
    restore_value: no
    initial_value: '6.25'   

#Atmospheric CO2 level for calibration purposes. Outdoor CO2 level during calibration. Usually 450, but it's better to clarify.
  - id: ATMOCO2
    type: float
    restore_value: no
    initial_value: '450'   

  - id: PARA
    type: float
    restore_value: no
    initial_value: '110.47'
  - id: PARB
    type: float
    restore_value: no
    initial_value: '-2.862'

#Parameters to model temperature and humidity dependence
  - id: CORA
    type: float
    restore_value: no
    initial_value: '0.00035'
  - id: CORB
    type: float
    restore_value: no
    initial_value: '0.02718'
  - id: CORC
    type: float
    restore_value: no
    initial_value: '1.39538'
  - id: CORD
    type: float
    restore_value: no
    initial_value: '0.0018'
  - id: CORE
    type: float
    restore_value: no
    initial_value: '-0.003333333'
  - id: CORF
    type: float
    restore_value: no
    initial_value: '-0.001923077'
  - id: CORG
    type: float
    restore_value: no
    initial_value: '1.130128205'

# Here you need to indicate the supply voltage of the MQ135 sensor. It can be measured with a voltmeter. Please note that the rated power will not always be accurate.
  - id: volt_resolution
    type: float
    restore_value: no
    initial_value: '5.0'  

# 1 for Exponential, 2 for Linear
  - id: regression_method
    type: int
    restore_value: no
    initial_value: '1'




light: 



button:
  - platform: template
    id: calibration
    name: "Calibrate Sensor"
    icon: mdi:lock-reset
    on_press:   
      then:
         - lambda: |-
            id(RZERO) = id(corrected_r_zero).state;
            id(ATMOCO2) = id(ppm_co2).state; 
    entity_category: config
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 77   


  - platform: restart
    name: "System restart"
    entity_category: config
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 60     

  - platform: factory_reset
    name: "Return to Factory settings"
    entity_category: config
    web_server: 
      web_server_id: webserver_sort
      sorting_group_id: critic_group    
      sorting_weight: 61     


switch:

sensor:
 
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    id: acilistan_gecen_sure_seconds
    internal: True

  - platform: template
    name: "Temperature"
    lambda: |-
      return  (id(temp).state);
    unit_of_measurement: "°C"
    accuracy_decimals: 0  
    id: temp_ort
    device_class: temperature
    icon: mdi:home-thermometer-outline
    web_server: 
          web_server_id: webserver_sort
          sorting_group_id: info_group
          sorting_weight: 16    
     
  - platform: copy  
    name: "Apparent temperature"
    id: feels_like
    accuracy_decimals: 0
    device_class: temperature
    icon: mdi:thermometer-lines
    source_id:  temp
    filters:
      - lambda:   return round(id(temp).state + ( ( (id(hum).state / 100) * 6.105 * 2.71828 *  ((17.27 * id(temp).state) / (237.7 + id(temp).state))  ) * 0.33 ) - 4  ); 
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: info_group
        sorting_weight: 27    

  - platform: absolute_humidity
    name: "Absolute Humidity"
    id: absolute_hum
    temperature: temp
    device_class: absolute_humidity
    icon: mdi:water-opacity
    humidity: hum
    accuracy_decimals: 0
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: info_group
        sorting_weight: 29
        
  - platform: dht # DHT11 sensor
    pin: GPIO0
    model: DHT11
    id: dht_sensoru
    
    temperature:
      id: temp
      internal: True
      name: "Temperature"
      accuracy_decimals: 0
      icon: mdi:home-thermometer-outline
      web_server: 
        web_server_id: webserver_sort
        sorting_group_id: info_group
        sorting_weight: 26     
    
    humidity:
      id: hum
      name: "Humudity"
      icon: mdi:water-percent
      web_server: 
        web_server_id: webserver_sort
        sorting_group_id: info_group
        sorting_weight: 28     
 

  - platform: adc # MQ135 sensor
    pin: GPIO4
    name: "Gas ADC"
    update_interval: 1s
    filters:
      - multiply: 3.3 # for ESP32 C6 Mini
    accuracy_decimals: 4
    unit_of_measurement: V
    id: sensor_volt
    internal: True

  - platform: template
    #Linearization of the temperature dependency curve under and above 20 degree C
    #below 20degC: fact = a * t * t - b * t - (h - 33) * d
    #above 20degC: fact = a * t + b * h + c
    #this assumes a linear dependency on humidity
    #getCorrectionFactor
    name: "Correction Factor"
    lambda: |-
      if (id(temp).state<20) {
        return (id(CORA) * id(temp).state * id(temp).state - id(CORB) *
          id(temp).state + id(CORC) - (id(hum).state - 33.) * id(CORD));
      } else {
        return (id(CORE) * id(temp).state + id(CORF) * id(hum).state + id(CORG));
      }
    update_interval: 10s
    accuracy_decimals: 6
    id: correction_factor
    internal: True

  - platform: template
    #Get the resistance of the sensor, ie. the measurement value @return The sensor resistance in kOhm
    # RS = [(VC x RL) / VRL] - RL
    # RS_air = ((5.14*1.0)/sensor_volt)-1.0 Calculate RS in fresh air 
    #getResistance
    name: "Resistance"
    lambda: |-
      return ((id(volt_resolution)*id(RLOAD)/id(sensor_volt).state) - id(RLOAD));
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: resistance
    internal: True

  - platform: template
    # Get the resistance of the sensor, ie. the measurement value correctedfor temp/hum @return The corrected sensor resistance kOhm
    # getCorrectedResistance
    name: "Corrected Resistance"
    lambda: |-
      return (id(resistance).state / id(correction_factor).state);
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: corrected_resistance
    internal: True

  - platform: template
    # Get the ppm of CO2 sensed (assuming only CO2 in the air). The ppm of CO2 in the air
    # getPPM
    name: "PPM CO2 reading" 
    id: ppm_co2
    internal: False  
    lambda: |-
      if (id(regression_method)==1) {
        return (id(PARA) * pow((id(resistance).state / id(RZERO)), id(PARB)));
      } else {
        return (pow(10, (log10(id(resistance).state / id(RZERO)) - id(PARB)) / id(PARA)));
      }
    update_interval: 1s
    unit_of_measurement: ppm
    icon: mdi:molecule-co2

    accuracy_decimals: 0
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 75

  - platform: template
    # Get the ppm of CO2 sensed (assuming only CO2 in the air), corrected  for temp. The ppm of CO2 in the air
    # getCorrectedPPM

    # https://www.co2meter.com/blogs/news/co2-ppm
    # summary 
    # 
    # Carbon Dioxide (CO2) 
    #       250-400 ppm 	Normal background concentration in outdoor ambient air
    #     400-1,000 ppm   Concentrations typical of occupied indoor spaces with good air exchange
    #   1,000-1,500 ppm   Complaints of drowsiness and poor air.
    #   1,500-2,000 ppm 	Complaints of drowsiness and poor air.
    #   2,000-5,000 ppm  	Headaches, sleepiness and stagnant, stale, stuffy air. Poor concentration, loss of attention, increased heart rate and slight nausea may also be present.
    #         5,000 ppm 	Workplace exposure limit (as 8-hour TWA) in most jurisdictions.
    #       >40,000 ppm 	Exposure may lead to serious oxygen deprivation resulting in permanent brain damage, coma, even death.

    name: "CO₂ level"
    lambda: |-
      if (id(regression_method)==1) {
        return (id(PARA) * pow((id(corrected_resistance).state / id(RZERO)), id(PARB)));
      } else {
        return (pow(10, (log10(id(corrected_resistance).state / id(RZERO)) - id(PARB)) / id(PARA)));
      }
    update_interval: 1s
    unit_of_measurement: ppm
    id: corrected_ppm_co2
    accuracy_decimals: 0
    icon: mdi:molecule-co2
    web_server: 
      web_server_id: webserver_sort
      sorting_group_id: info_group
      sorting_weight: 34 
    filters:
      - skip_initial: 30  
      - delta: 0.1%  
      - sliding_window_moving_average:
          window_size: 30  
          send_every: 5


  - platform: template
    # Get the resistance RZero of the sensor for calibration purposes. The sensor resistance RZero in kOhm
    # getRZero
    name: "RZero"
    internal: True
    lambda: |-
      return (id(resistance).state / pow((id(ATMOCO2) / id(PARA)), (1./id(PARB))));
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: r_zero
    

  - platform: template
    # Get the corrected resistance RZero of the sensor for calibration purposes. The corrected sensor resistance RZERO in kOhm for ATMOCO2 level
    # getCorrectedRZero
    name: "RZERO reading"
    lambda: |-
      return (id(corrected_resistance).state / pow((id(ATMOCO2) / id(PARA)), (1./id(PARB))));
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
    icon: mdi:resistor
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 73 
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: corrected_r_zero
    internal: False 
                    # https://github.com/Bobbo117/MQ135-Air-Quality-Sensor
                    # https://www.reddit.com/r/arduino/comments/1b5xp9t/seeking_help_to_calibrate_the_mq135_module/
                    # https://www.google.com/search?q=how+to+calibrate+mq+135
                     

binary_sensor:


text_sensor:
  - platform: template
    name: 'RZERO Default'
    id: 'rzero_value'
    lambda: |-
      return {to_string(id(RZERO))};
    update_interval: 10s
    icon: mdi:resistor
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 72 


  - platform: template
    name: 'PPM CO2 Default'
    id: 'atm0co2_value'
    lambda: |-
      return {to_string(id(ATMOCO2))};
    update_interval: 10s
    icon: mdi:molecule-co2
    web_server: 
        web_server_id: webserver_sort
        sorting_group_id: critic_group   
        sorting_weight: 74
